### ISSUE TITLE
How to deal with non-positive nr_pigs?

### ISSUE THREAD

**Issue by CarlijnB** [digivet-consortium/movenet#25]
Danish data sometimes has moves with nr_pigs = 0, due to only containers of dead pigs being moved
Additionally, use of coarsen_weight can turn nr_pigs into 0 or negative numbers.

How should we deal with these?

True 0s (e.g. as in Danish data):
- Always remove these at reading/reformatting stage?
- Allow for optional removal? (Separate function/option to do so)
- Keep in? (unsure how this then gets processed by igraph etc - will check)

Artificial 0s (from coarsen_weight):
- Keep as they are (but may affect network analysis)? (unsure how this gets processed by igraph etc - will check)
- Change to 1, so as to def keep the connection?
- Any other ideas?

@mdenwood , @magicicada any views?

**Comment by mdenwood** [comment]
I'd say that the true zeros should be removed before processing, as they do not reflect movements of animals. Arguably I should have thought to do this myself - sorry!

The artificial zeros are a bit trickier.  I imagine that igraph would treat edges with weights of zero as non-existent, which I think we don't want to do. Re-assigning them to 1 is better, but we will end up with a big artificial spike at 1 if we do that. So I think I would prefer for course_weight to ensure that all weights have a minimum edge weight of 1 by e.g. sampling from a truncated distribution for the replacement (which it could do by repeatedly re-sampling anything with a zero weight until they are all positive).

**Comment by CarlijnB** [comment]
To solve jitter() generating negative numbers, at some point I could also use absolute values, on anything negative.

What I'm most unsure about, is rounding. Current implementation works by order of magnitude (simply via base R round()). I could make it so that all that would normally be rounded down to 0, instead are rounded up? e.g. if rounding to 10s, minimum is 10?

**Comment by mdenwood** [comment]
Yes I think the best thing is to round to the minimum magnitude, rather than 0, in that situation. The disease risk of moving 1 animal is much closer to that of moving 10 than 0, anyway!

I am not aware of any guidelines for rounding data in Denmark, although the human health authorities require that tallies be a minimum of 5 (and from a population size of at least 20) to be sufficiently anonymised - which I guess is related to rounding (although we normally just use "0-4" to distinguish these from true 5). That doesn't apply to animals though. I'll try to check if the danish veterinary and food authority have any guidelines, but I doubt it (partly because the movement data for cattle are theoretically all public anyway).

**Comment by CarlijnB** [comment]
Reading that, and similar from HESA - maybe I should adapt the rounding to use plyr::round_any() , meaning one could round to multiples of any number, rather than only powers of ten.

**Comment by CarlijnB** [comment]
For jitter, I have now implemented @mdenwood 's suggestion to reject & resample negative replacement values.
I have also changed from using base jitter to explicitly using `data + runif(n, -jitter, +jitter)` so as to allow easy replacement with an alternative distribution if preferred. 
@mdenwood , @magicicada - should jitter follow uniform distribution , normal distribution, something different?

For rounding I have now implemented round_any, so as to allow rounding of data points to multiples of any number.
Additionally, data points < `round` (the number to round to) are now being set to `round`  as minimum.
